---
# possibly saved as tasks/foo.yml

- name: ping test
  ping:

#Check if Mailx is installed
- name: Install Mailx
  yum: name=mailx state=latest


#upload the mail.conf file to the default users homefolder preferably not root
- name: Copy mailrc folder to home directory
  copy: src={{mailrcsrc}} dest={{mailrcdest}} owner=root group=root mode=644

#upload a mozilla Firefox folder so ssl authentication works. 
- name: Copy Mozilla folder to home directory folder for SSL certs
  copy: src={{mozillasrc}} dest={{mozilladest}} owner=root group=root mode=644

- name: Make Symbolic Link for mailx to email
  shell: ln -s /bin/mailx /bin/email

