---

- name: Test Connection
  ping:

- name: Copy get-pip.py up to steam home directory
  copy: src={{pip_source}} dest={{pip_dest}} owner=steam group=steam mode=744

- name: Install Pip Tools
  shell: "sudo python /home/steam/get-pip.py"

